---
title: "Measurement Chains"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Measurement Chains}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

con_vars <- sprintf("MESSKETTEN_%s", c("SERVER", "USER", "PASSWORD"))
con <- list(server = Sys.getenv(con_vars[1]),
            user = Sys.getenv(con_vars[2]),
            pw = Sys.getenv(con_vars[3])
)

is_defined <- sapply(con, stringr::str_length) > 0

con_defined <- all(is_defined)

```

```{r setup,  eval = con_defined}
library(kwb.geosalz)


mc_metadata <- kwb.geosalz::get_measurementchains_metadata()

str(mc_metadata)
DT::datatable(mc_metadata)

mc_files <- kwb.geosalz::get_measurementchains_files()

str(mc_files)
head(mc_files)

target_directory <- tempdir()

csv_files <- kwb.geosalz::download_measurementchains_data(
  sftp_paths = mc_files$sftp_path,
  target_directory,
  debug = TRUE)

csv_files

mc_data_single <- kwb.geosalz::read_measurementchains_data(
  csv_files,
  run_parallel = FALSE,
  debug = TRUE)
mc_data_parallel <- kwb.geosalz::read_measurementchains_data(
  csv_files,
  run_parallel = TRUE,
  debug = TRUE)

identical(mc_data_single, mc_data_parallel)


mc_data_parallel



```
