---
title: "Wasserportal"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Wasserportal}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Define Helper Functions

```{r define_helpers}
library(kwb.geosalz)

add_label <- function(
    df, 
    columns = c("Nummer", "start", "end", "n", "interval")
)
{
  df %>%
    dplyr::mutate(label = wasserportal::columns_to_labels(
      data = df,
      columns = columns,
      fmt = "<p>%s: %s</p>",
      sep = ""
    ))
}

get_data_stats <- function(df, group_col = "Messstellennummer") {
  df %>%
    dplyr::group_by(.data[[group_col]]) %>%
    dplyr::summarise(
      start = min(as.Date(.data$Datum)),
      end = max(as.Date(.data$Datum)),
      period = diff(c(.data$start, .data$end)),
      n = dplyr::n(),
      interval = round(.data$period / .data$n, 0)
    )
}

difftime_to_numeric <- function(df) {
  df %>%  
    dplyr::rename(
      period_days = .data$period, 
      interval_days = .data$interval
    ) %>% 
    dplyr::mutate(
      period_days = as.numeric(.data$period_days),
      interval_days = as.numeric(.data$interval_days)
    )
}

remove_na_and_geometry <- function(df) {
  df %>%
    kwb.utils::removeColumns("label") %>%
    kwb.utils::removeEmptyColumns(dbg = FALSE) %>%
    remove_geometry()
}

remove_geometry <- function(df) {
  sf::st_geometry(df) <- NULL
  df
}
```

```{r setup}
swl_map <- NULL
gwl_map <- NULL
gwq_map <- NULL

swl_data_stats_export <- NULL
gwl_data_stats_export <- NULL
gwq_chloride_data_stats_export <- NULL
```

```{r}
library(kwb.geosalz)

### Load SVM Boundaries
svm <- "extdata/gis/shapefiles/svm_south.shp" %>%
  system.file(package = "kwb.geosalz") %>%
  sf::st_read() %>%
  # Transform to required coordinate reference system (CRS)
  sf::st_transform(crs = 4326)

sf::st_crs(svm)

polygon_svm_fri <- svm$geometry[svm$name == "Friedrichshagen"]

stations <- wasserportal::get_stations()
```

```{r surfacewater_level}
try({
  
  # Surface water - water levels
  swl_master <- wasserportal::get_wasserportal_masters_data(
    master_urls = stations$overview_list$surface_water.water_level %>%
      dplyr::filter(.data$Betreiber == "Land Berlin") %>%
      dplyr::pull(.data$stammdaten_link)
  ) 
  
  swl_master_sf <- swl_master %>%
    kwb.geosalz::convert_to_sf() %>%
    sf::st_filter(y = polygon_svm_fri) %>%
    add_label(columns = c("Nummer", "Gewaesser", "Auspraegung", "Betreiber"))
  
  swl_master <- swl_master %>% 
    dplyr::filter(.data$Nummer %in% swl_master_sf$Nummer) 
  
  readr::write_csv2(swl_master, file = "swl_master.csv")
  
  swl_data_list <- stats::setNames(
    lapply(swl_master$Nummer, function(station) {
      wasserportal::read_wasserportal(
        station = station, 
        from_date = "1900-01-01",
        variables = "ows", 
        type = "daily",
        stations_crosstable = stations$crosstable
      )
    }), 
    nm = swl_master$Nummer
  )
  
  column_level_zero <- "Pegelnullpunkt_m_NHN"
  key_columns <- c("Nummer", column_level_zero)

  swl_data <- stats::setNames(
    lapply(names(swl_data_list), function(name) {
      swl_data_list[[name]][[1]]
    }),
    names(swl_data_list)
  ) %>% 
    dplyr::bind_rows(.id = "Messstellennummer") %>% 
    dplyr::mutate(Datum = as.Date(.data$Datum, format = "%d.%m.%Y")) %>% 
    dplyr::filter(.data$Tagesmittelwert != -777) %>% 
    dplyr::rename(
      Tagesmittelwert_cm_ueber_Pegelnullpunkt = "Tagesmittelwert"
    ) %>% 
    dplyr::left_join(
      swl_master[, ..key_columns],
      by = c(Messstellennummer = "Nummer")
    ) %>%  
    dplyr::mutate(
      Tagesmittelwert_Pegelstand_mNN = as.numeric(.data[[column_level_zero]]) +
        .data$Tagesmittelwert_cm_ueber_Pegelnullpunkt / 100
    ) %>% 
    dplyr::select(- .data[[column_level_zero]])
  
  readr::write_csv2(swl_data, file = "swl_data.csv")
  
  swl_data_stats <- get_data_stats(swl_data)
  
  swl_data_stats_export <- swl_master_sf %>% 
    remove_na_and_geometry() %>%
    dplyr::left_join(
      difftime_to_numeric(swl_data_stats),
      by = c("Nummer" = "Messstellennummer")
    )
  
  readr::write_csv2(swl_data_stats_export, file = "swl_data_stats.csv")
})
```

```{r groundwater_level}
try({

  gwl_master <- jsonlite::fromJSON(
    "https://kwb-r.github.io/wasserportal/stations_gwl_master.json"
  )
  
  gwl_master_sf <- gwl_master %>%
    kwb.geosalz::convert_to_sf() %>%
    sf::st_filter(y = polygon_svm_fri)
  
  gwl_master <- gwl_master %>% 
    dplyr::filter(.data$Nummer %in% gwl_master_sf$Nummer)
  
  readr::write_csv2(gwl_master, file = "gwl_master.csv")
  
  gwl_data <- data.table::rbindlist(
    lapply(gwl_master$Nummer, function(id) {
      wasserportal::read_wasserportal_raw_gw(station = id, stype = "gwl")
    })
  )
  
  readr::write_csv2(gwl_data, file = "gwl_data.csv")
  
  gwl_data_stats <- get_data_stats(gwl_data) 
  
  gwl_data_stats_export <- gwl_master_sf %>% 
    remove_na_and_geometry() %>%
    dplyr::left_join(
      difftime_to_numeric(gwl_data_stats),
      by = c("Nummer" = "Messstellennummer")
    )
  
  readr::write_csv2(gwl_data_stats_export, file = "gwl_data_stats.csv")
  
  gwl_master_stats <- gwl_master %>%
    dplyr::left_join(gwl_data_stats, by = c("Nummer" = "Messstellennummer")) %>%
    add_label()
  
})
```

```{r groundwater_quality}
try({
  
  gwq_master <- jsonlite::fromJSON(
    "https://kwb-r.github.io/wasserportal/stations_gwq_master.json"
  )

  gwq_master_sf <- gwq_master %>%
    kwb.geosalz::convert_to_sf() %>%
    sf::st_filter(y = polygon_svm_fri)
  
  gwq_master <- gwq_master %>% 
    dplyr::filter(.data$Nummer %in% gwq_master_sf$Nummer)
  
  readr::write_csv2(gwq_master, file = "gwq_master.csv")
  
  gw_master <- gwl_master %>%  
    dplyr::full_join(gwq_master) %>% 
    dplyr::mutate(Nummer = as.integer(.data$Nummer)) %>% 
    dplyr::arrange(.data$Nummer)
  
  readr::write_csv2(gw_master, file = "gw_master.csv")
  
  gwq_data <- jsonlite::fromJSON(
    "https://kwb-r.github.io/wasserportal/stations_gwq_data.json"
  ) %>%
    dplyr::filter(.data$Messstellennummer %in% gwq_master$Nummer)
  
  readr::write_csv2(
    gwq_data,
    file = "gwq_data.csv"
  )
  
  gwq_chloride_data <- gwq_data %>%
    dplyr::filter(.data$Parameter == "Chlorid")
  
  readr::write_csv2(
    gwq_chloride_data,
    file = "gwq_chloride_data.csv"
  )
  
  gwq_chloride_master <- gwq_master %>% 
    dplyr::filter(.data$Nummer %in% gwq_chloride_data$Messstellennummer)
  
  readr::write_csv2(
    gwq_chloride_master,
    file = "gwq_chloride_master.csv"
  )
  
  gwq_chloride_data_stats <- gwq_chloride_data %>%
    get_data_stats()
  
  gwq_chloride_data_stats_export <- gwq_chloride_master %>%
    kwb.geosalz::convert_to_sf() %>% 
    remove_na_and_geometry() %>%
    dplyr::mutate(Nummer = as.integer(.data$Nummer)) %>% 
    dplyr::left_join(
      difftime_to_numeric(gwq_chloride_data_stats),
      by = c("Nummer" = "Messstellennummer")
    )
  
  readr::write_csv2(
    gwq_chloride_data_stats_export,
    file = "gwq_chloride_data_stats.csv"
  )
  
  gwq_chloride_master_stats <- gwq_chloride_master %>%
    dplyr::mutate(Nummer = as.integer(.data$Nummer)) %>%
    dplyr::left_join(
      gwq_chloride_data_stats, 
      by = c("Nummer" = "Messstellennummer")
    ) %>%
    add_label()
  
  readr::write_csv2(
    gwq_chloride_master_stats, 
    file = "gwq_chloride_master_stats.csv"
  )
})
```


```{r print_maps}
try({
  
  # Print Map
  basemap <- svm %>%
    leaflet::leaflet() %>%
    leaflet::addTiles() %>%
    leaflet::addProviderTiles(leaflet::providers$CartoDB.Positron) %>%
    leaflet::addPolygons(color = "red", fill = FALSE)
  
  swl_map <- basemap %>%
    leaflet::addCircles(
      data = swl_master_sf,
      color = "blue",
      opacity = 0.4,
      label = lapply(swl_master_sf$label, htmltools::HTML)
    ) %>%
    leaflet::addLegend(
      position = "topright",
      colors = c("red", "darkblue"),
      labels = c("SVM Modellgrenze", "OW-Stand (Wasserportal)"),
      title = "Legende"
    )
  
  gwl_map <- basemap %>%
    leaflet::addCircles(
      data = kwb.geosalz::convert_to_sf(gwl_master_stats),
      color = "blue",
      opacity = 0.4,
      label = lapply(gwl_master_stats$label, htmltools::HTML)
    ) %>%
    leaflet::addLegend(
      position = "topright",
      colors = c("red", "blue"),
      labels = c("SVM Modellgrenze", "GW-Stand (Wasserportal)"),
      title = "Legende"
    )
  
  gwq_map <- basemap %>%
    leaflet::addCircles(
      data = kwb.geosalz::convert_to_sf(gwq_chloride_master_stats),
      color = "orange",
      opacity = 0.4,
      label = lapply(gwq_chloride_master_stats$label, htmltools::HTML)
    ) %>%
    leaflet::addLegend(
      position = "topright",
      colors = c("red", "orange"),
      labels = c("SVM Modellgrenze", "GW-G\u00FCte (Wasserportal)"),
      title = "Legende"
    )
  
  print(swl_map)
  print(gwl_map)
  print(gwq_map)
})

```

## Maps 

Save maps for full page view:

```{r save_swl_map, eval = !is.null(swl_map)}
htmlwidgets::saveWidget(
  swl_map, 
  "./map_swl.html", 
  title = "SW level"
)
```

```{r save_gwl_map, eval = !is.null(gwl_map)}
htmlwidgets::saveWidget(
  gwl_map, 
  "./map_gwl.html", 
  title = "GW level"
)
```

```{r save_gwq_map, eval = !is.null(gwq_map)}
htmlwidgets::saveWidget(
  gwq_map, 
  "./map_gwq.html", 
  title = "GW quality (Chloride)"
)
```

**Links to full-page view maps:**

* [https://kwb-r.github.io/kwb.geosalz/map_swl.html](../map_swl.html)

* [https://kwb-r.github.io/kwb.geosalz/map_gwl.html](../map_gwl.html)

* [https://kwb-r.github.io/kwb.geosalz/map_gwq.html](../map_gwq.html)


## Datasets


### Surface Water

* [https://kwb-r.github.io/kwb.geosalz/swl_master.csv](../swl_master.csv)

* [https://kwb-r.github.io/kwb.geosalz/swl_data.csv](../swl_data.csv)

* [https://kwb-r.github.io/kwb.geosalz/swl_data_stats.csv](../swl_data_stats.csv)

### Groundwater

#### Master Data 

for [Groundwater Levels](#groundwater-levels) and [Groundwater Levels](#groundwater-quality)

* [https://kwb-r.github.io/kwb.geosalz/gw_master.csv](../gw_master.csv)

#### Groundwater Levels

* [https://kwb-r.github.io/kwb.geosalz/gwl_master.csv](../gwl_master.csv)

* [https://kwb-r.github.io/kwb.geosalz/gwl_data.csv](../gwl_data.csv)

* [https://kwb-r.github.io/kwb.geosalz/gwl_data_stats.csv](../gwl_data_stats.csv)

#### Groundwater Quality 

* [https://kwb-r.github.io/kwb.geosalz/gwq_master.csv](../gwq_master.csv)

* [https://kwb-r.github.io/kwb.geosalz/gwq_data.csv](../gwq_data.csv)


* [https://kwb-r.github.io/kwb.geosalz/gwq_chloride_master.csv](../gwq_chloride_master.csv)

* [https://kwb-r.github.io/kwb.geosalz/gwq_chloride_master_stats.csv](../gwq_chloride_master_stats.csv)

* [https://kwb-r.github.io/kwb.geosalz/gwq_chloride_data.csv](../gwq_chloride_data.csv)


### Tables

#### SW Levels 

```{r tbl_swl, eval = !is.null(swl_data_stats_export)}
DT::datatable(swl_data_stats_export)
```

#### GW Levels 

stats for `groundwater levels`

```{r tbl_gwl, eval = !is.null(gwl_data_stats_export)}
DT::datatable(gwl_data_stats_export)
```

#### GW Quality 

stats for `Chloride`

```{r tbl_gwq, eval = !is.null(gwq_chloride_data_stats_export)}
DT::datatable(gwq_chloride_data_stats_export)
```
